### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by Chuldun** [b-fullam/Automating-VirusTotal-APIv3-for-IPs-and-URLs#4]
Please help me resolve the following error. I followed the tutorial and had no problems with the installation. I tried to enter an IP list from a txt file and got the error below. Please help me fix it as I am a beginner in Python coding.

```
Traceback (most recent call last):
  File "/home/haha/python-vt/vt-ip-url-analysis.py", line 459, in <module>
    urlReportIPLst(args.ip_list)
  File "/home/haha/python-vt/vt-ip-url-analysis.py", line 322, in urlReportIPLst
    urlReport(i)
  File "/home/haha/python-vt/vt-ip-url-analysis.py", line 104, in urlReport
    epoch_time = (decodedResponse["data"]["attributes"]["last_analysis_date"])
KeyError: 'data'
```

**Comment by koreytm** [comment]
I'm also getting this error, in case anyone can assist.
